# Funding

If you find PetHive useful, please consider supporting the project:

## 💖 Support Options

### GitHub Sponsors
[Sponsor on GitHub](https://github.com/sponsors/YOUR_USERNAME)

### Buy Me a Coffee
[Buy Me a Coffee](https://buymeacoffee.com/YOUR_USERNAME)

### PayPal
[Donate via PayPal](https://paypal.me/YOUR_USERNAME)

### Cryptocurrency
- **Bitcoin**: YOUR_BTC_ADDRESS
- **Ethereum**: YOUR_ETH_ADDRESS

---

Your support helps maintain and improve PetHive! 🐾
