#!/bin/bash
# Vercel Environment Variables Setup for PetHive
# This script helps you set environment variables needed for deployment

# Your Vercel project details
VERCEL_URL="https://pethive-psi.vercel.app"
API_URL="${VERCEL_URL}/api"

echo "🔧 PetHive Vercel Setup - Environment Variables"
echo "================================================"
echo ""
echo "Your Deployment URL: $VERCEL_URL"
echo "Your API URL: $API_URL"
echo ""
echo "⚠️  MANUAL SETUP REQUIRED:"
echo "================================================"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your 'pethive-psi' project"
echo "3. Click 'Settings' → 'Environment Variables'"
echo ""
echo "4. Add these environment variables:"
echo ""
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ PRODUCTION ENVIRONMENT VARIABLES                │"
echo "   ├─────────────────────────────────────────────────┤"
echo "   │ Name: VITE_API_URL                              │"
echo "   │ Value: $API_URL"
echo "   │ Environments: Production                         │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ Name: CLIENT_URL                                │"
echo "   │ Value: $VERCEL_URL"
echo "   │ Environments: Production                         │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ Name: DATABASE_URL                              │"
echo "   │ Value: [YOUR_POSTGRES_CONNECTION_STRING]        │"
echo "   │ Environments: Production                         │"
echo "   │                                                 │"
echo "   │ Get from:                                       │"
echo "   │ - Vercel Postgres: vercel.com/dashboard/storage │"
echo "   │ - Neon: neon.tech                               │"
echo "   │ - Supabase: supabase.com                         │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ Name: SESSION_SECRET                            │"
echo "   │ Value: [GENERATE_RANDOM_STRING]                 │"
echo "   │ Environments: Production                         │"
echo "   │                                                 │"
echo "   │ Generate: openssl rand -base64 32               │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ Name: NODE_ENV                                  │"
echo "   │ Value: production                               │"
echo "   │ Environments: Production                         │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "5. After adding variables, click 'Redeploy' on the"
echo "   Deployments page"
echo ""
echo "6. Verify deployment:"
echo "   - Visit: $API_URL"
echo "   - Should show: {\"message\": \"PetHive API\", ...}"
echo ""
echo "   - Visit: $VERCEL_URL/health"
echo "   - Should show: {\"status\": \"ok\"}"
echo ""
echo "✅ Once environment variables are set and app is"
echo "   redeployed, the 404 error should be fixed!"
